[[main]]
  identifier = "about"
  name = "简介"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "历史文章"
  url = "archive"
  weight = 2

[[main]]
  identifier = "presentation"
  name = "展示"
  url = "presentation"
  weight = 3

[[main]]
  identifier = "gallery"
  name = "相册"
  url = "gallery"
  weight = 4
    
[[main]]
  parent = "gallery"
  name = "书籍封面"
  url = "gallery/cartoon"

[[main]]
  parent = "gallery"
  name = "杂志封面"
  url = "gallery/photo"

[[main]]
  identifier = "posts"
  name = "博客"
  url = "posts"
  weight = 5

#[[main]]
#  identifier = "showcase"
#  name = "Showcase"
#  url = "showcase"
#  weight = 6

#[[main]]
#  identifier = "publication"
#  name = "Pub"
#  url = "publication"
#  weight = 7